// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routers

import (
	"github.com/paper.id.disbursement/api/v1/disbursements"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Disbursements(db *gorm.DB) *disbursements.DisbursementHandler {
	disbursementRepository := disbursements.NewDisbursementRepository(db)
	disbursementUseCase := disbursements.NewDisbursementUseCase(disbursementRepository)
	disbursementHandler := disbursements.NewDisbursementHandler(disbursementUseCase)
	return disbursementHandler
}
